### ISSUE TITLE
vendor.css contains Pikaday CSS when excludePikadayAssets is true

### ISSUE THREAD

**Issue by scottwernervt** [adopted-ember-addons/ember-pikaday#122]
The Pikaday assets are not being excluded from `vendor.css` when `excludePikadayAssets: true`.

ember-pikaday = 2.2.0
pikaday = 1.4.0

**Repeat Issue**
1. Set `excludePikadayAssets: true` in `ember-cli-build.js`

```javascript
// ember-cli-build.js
var app = new EmberApp(defaults, {
    emberPikaday: {
      excludePikadayAssets: true,
    },
});
```

2. Open http://localhost:4200/assets/vendor.css (ember-app/dist/assets/vendor.css)
```css

/*!
 * Pikaday
 * Copyright © 2014 David Bushell | BSD & MIT license | http://dbushell.com/
 */

.pika-single {
    z-index: 9999;
    display: block;
    position: relative;
    color: #333;
    background: #fff;
    border: 1px solid #ccc;
    border-bottom-color: #bbb;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}

...
```
